### ISSUE TITLE
Typo error in README

### ISSUE THREAD

**Issue by aguilaj** [Liinkiing/node-webpack-typescript-starter#1]
In your README file you write "separe". This is not an english word. Please consider using separate, as it hurts my eyes.

**Comment by Liinkiing** [comment]
Can you do a PR please and a test to reproduce the case? Thank you for contributing!!!

**Comment by aguilaj** [comment]
Please give me rights to push, fix ready

**Comment by Liinkiing** [comment]
Thank you for your time! Really appreciating it! But you must fork the repo and submit a PR 
![4MHY0kQ](https://user-images.githubusercontent.com/17753997/69422261-8c795600-0d23-11ea-8afb-743c1f2464fe.gif)

**Comment by Liinkiing** [comment]
Closed by #2
